branches:
  except:
    - alpha-react-pdf
addons:
  ssh_known_hosts:
    - rey.webhouse.net
cache: npm
before_deploy:
  - openssl aes-256-cbc -K $encrypted_257f186ccb94_key -iv $encrypted_257f186ccb94_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    script: bash scripts/deploy.sh master $TRAVIS_BUILD_DIR
    skip_cleanup: true
    on:
      branch: master
  - domain: https://waterworks-senti.surge.sh
    project: "./build"
    provider: surge
    skip_cleanup: true
    on:
      branch: beta
language: node_js
node_js:
  - stable
notifications:
  email:
    recipients:
      - at@webhouse.dk
    on_success: never
    on_failure: always
script:
  - npm run-script build
  - cp ./build/index.html ./build/200.html
